<?php

namespace app\admin\common;

use think\Controller;
use think\Session;

class Base extends Controller{
    //自动运行初始化方法
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        define('USER_ID',Session::get('user_id'));
    }

    //是否以登录
    public function isLogin(){
        if(is_null(USER_ID)){
            $this->error('请登录后进行操作...','login/index');
        }
    }
    //是否重复登录
    public function repeatLogin(){
        if(!is_null(USER_ID)){
            $this->error('用户以登录...','index/index');
        }
    }
}